wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 5
      4: 3.8.5
      5: 0.10.33
      8:
      - 1
      - 3
      - 5
learning_rate:
  desc: null
  value: 0.1
